### PR TITLE
Removed config yml file

### LINKED ISSUE #227: Remove seemingly unused _config.yml file
Perhaps I am mistaken, but I don't believe that the [`_config.yml` file](https://github.com/vprusso/toqito/blob/master/_config.yml) is being used and can most likely be removed.

### PR DESCRIPTION
**Pull request by vprusso**
Closes #227

### CODE REVIEW

**Review by purva-thakre — APPROVED** [review]
LGTM. Feel free to merge!

**Comment by vprusso** [comment]
Worked really hard on that one :). Didn't seem to break anything, so I think we can go ahead and merge it in. Thanks for the review!

**Comment by purva-thakre** [comment]
I think this file was related to Github pages. I recognize the theme because I have attempted to use the same theme for multiple attempts at setting up my personal blog. Jekyll and Github pages are quite the upward learning curve. 

Perhaps before deciding to use Sphinx and RTD, you tried to use Github pages to set up the docs page?

**Comment by vprusso** [comment]
Very likely. I'm quite sure that was added during the earlier part of the project when I was going through and experimenting with different documentation solutions. Definitely an artifact of my previous stumblings in the dark.

**Pull request merged**
