### PR TITLE
Add support for GitHub citations

### PR DESCRIPTION
**Pull request by paniash**
## Description
Added some aesthetic and convenience features.

## Todos
Notable points that this PR has either accomplished or will accomplish.
  -  [X] Add syntax highlighting for bibtex entry in readme.
  -  [X] Add a citation file for GitHub's citation feature.

## Status
-  [X] Ready to go

### CODE REVIEW

**Comment by vprusso** [comment]
Hi @paniash. Thank you for your contribution!

It looks like the build is failing (for a reason that is most definitely not your fault, as it's occurring in a location that you didn't touch).

I'm wondering however if you would be kind enough to include the fixes for this failure in your diff. Basically, you would change any usage of `list()` to `[]` in the `nonlocal_games/extended_nonlocal_game.py` and `nonlocal_game.py` files.

If you can do that, I'd be much obliged! Thank you again, and thank you again for your contribution!

**Comment by paniash** [comment]
> I'm wondering however if you would be kind enough to include the fixes for this failure in your diff. Basically, you would change any usage of `list()` to `[]` in the `nonlocal_games/extended_nonlocal_game.py` and `nonlocal_game.py` files.

Done!
 
> If you can do that, I'd be much obliged! Thank you again, and thank you again for your contribution!

😃

**Comment by paniash** [comment]
Any reason why the CI is failing though? Isn't `list()` and `[]` functionally the same?

**Review by vprusso — APPROVED** [review]

**Comment by vprusso** [comment]
Awesome, thank you! And as for why it doesn't like `list()` but prefers `[]` boils down to the linter that's being used. 

Thanks again!

**Pull request merged**
