### PR TITLE
Fix RTD build failure

### LINKED ISSUE #284: Failing docs build
Looks like the sphinx contrib package is causing the read the docs server to fail.

Running Sphinx v7.2.6

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/toqito/envs/latest/lib/python3.11/site-packages/sphinx/registry.py", line 447, in load_extension
    mod = import_module(extname)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/.asdf/installs/python/3.11.6/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sphinxcontrib.bibtex'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/toqito/envs/latest/lib/python3.11/site-packages/sphinx/cmd/build.py", line 293, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/toqito/envs/latest/lib/python3.11/site-packages/sphinx/application.py", line 233, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/toqito/envs/latest/lib/python3.11/site-packages/sphinx/application.py", line 406, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/toqito/envs/latest/lib/python3.11/site-packages/sphinx/registry.py", line 450, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension sphinxcontrib.bibtex (exception: No module named 'sphinxcontrib.bibtex')

Extension error:
Could not import extension sphinxcontrib.bibtex (exception: No module named 'sphinxcontrib.bibtex')

### PR DESCRIPTION
**Pull request by purva-thakre**
## Description
Fixes #284 

## Todos
Notable points that this PR has either accomplished or will accomplish.
  -  [ ] TODO 1

## Questions
-  [ ] Question1

## Status
-  [ ] Ready to go

### CODE REVIEW

**Comment by purva-thakre** [comment]
Don't know if the fix is as easy as this.

**Comment by vprusso** [comment]
Your guess is as good as mine. Unfortunately, not sure of a way to test this without merging, so let's give it a good! MWR! 🚀

**Comment by purva-thakre** [comment]
Looks like the build is still failing. Plus, I don't think the build passed for the changes in #279 as well. 

We can work on this on Thursday, if you want to.

**Comment by vprusso** [comment]
Sounds good. At least the error this time is different!

Extension error (sphinx.ext.autosummary):
Handler <function process_generate_options at 0x7f559ad2e840> for event 'builder-inited' threw an exception (exception: no module named toqito.channel_metrics)

**Comment by purva-thakre** [comment]
>At least the error this time is different!
Good to know! Looks like we might need to add Toqito to the `requirements.txt` file? Or figure out a way to clear the RTD cache [first.](https://stackoverflow.com/a/76149030) 

I don't have an RTD account. But I plan to set it up by Thursday. I was thinking we could work on enabling PR build preview on Thursday. Prevents the back and forth on what error you see on RTD, me trying to guess what might be the issue etc. 

https://docs.readthedocs.io/en/stable/guides/pull-requests.html

**Comment by vprusso** [comment]
Hmm, that's possible (although I'm not sure that `toqito` needs to be installed as a doc dependency.

Here's some output that might give a bit more info that (perhaps) may be helpfuL

```
python -m sphinx -T -E -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html
Running Sphinx v7.2.6
making output directory... done
checking bibtex cache... out of date
parsing bibtex file /home/docs/checkouts/readthedocs.org/user_builds/toqito/checkouts/latest/docs/books.bib... parsed 1 entries
parsing bibtex file /home/docs/checkouts/readthedocs.org/user_builds/toqito/checkouts/latest/docs/articles.bib... parsed 117 entries
[autosummary] generating autosummary for: _autosummary/toqito.channel_metrics.channel_fidelity.rst, _autosummary/toqito.channel_metrics.completely_bounded_spectral_norm.rst, _autosummary/toqito.channel_metrics.completely_bounded_trace_norm.rst, _autosummary/toqito.channel_metrics.diamond_norm.rst, _autosummary/toqito.channel_metrics.fidelity_of_separability.rst, _autosummary/toqito.channel_ops.apply_channel.rst, _autosummary/toqito.channel_ops.choi_to_kraus.rst, _autosummary/toqito.channel_ops.dual_channel.rst, _autosummary/toqito.channel_ops.kraus_to_choi.rst, _autosummary/toqito.channel_ops.partial_channel.rst, ..., rand.rst, references.rst, states.rst, tutorials.extended_nonlocal_games.rst, tutorials.nonlocal_games.rst, tutorials.rst, tutorials.state_distinguishability.rst, tutorials.state_exclusion.rst, tutorials.superdense_coding.rst, tutorials.xor_quantum_value.rst
WARNING: Failed to import toqito.state_opt.state_helper.
Possible hints:
* ModuleNotFoundError: No module named 'sympy'
* AttributeError: module 'toqito' has no attribute 'state_opt'
WARNING: Failed to import toqito.nonlocal_games.xor_game.
Possible hints:
* ModuleNotFoundError: No module named 'sympy'
* AttributeError: module 'toqito' has no attribute 'nonlocal_games'
WARNING: Failed to import toqito.nonlocal_games.nonlocal_game.
Possible hints:
* ModuleNotFoundError: No module named 'sympy'
* AttributeError: module 'toqito' has no attribute 'nonlocal_games'
WARNING: Failed to import toqito.nonlocal_games.extended_nonlocal_game.
Possible hints:
* ModuleNotFoundError: No module named 'sympy'
* AttributeError: module 'toqito' has no attribute 'nonlocal_games'
WARNING: Failed to import toqito.nonlocal_games.quantum_hedging.
Possible hints:
* ModuleNotFoundError: No module named 'sympy'
* AttributeError: module 'toqito' has no attribute 'nonlocal_games'

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/toqito/envs/latest/lib/python3.11/site-packages/sphinx/ext/autosummary/generate.py", line 503, in generate_autosummary_docs
    name, obj, parent, modname = import_by_name(entry.name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/toqito/envs/latest/lib/python3.11/site-packages/sphinx/ext/autosummary/__init__.py", line 655, in import_by_name
    raise ImportExceptionGroup('no module named %s' % ' or '.join(tried), exceptions)
sphinx.ext.autosummary.ImportExceptionGroup: no module named toqito.channel_metrics.channel_fidelity

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/toqito/envs/latest/lib/python3.11/site-packages/sphinx/events.py", line 97, in emit
    results.append(listener.handler(self.app, *args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/toqito/envs/latest/lib/python3.11/site-packages/sphinx/ext/autosummary/__init__.py", line 814, in process_generate_options
    generate_autosummary_docs(genfiles, suffix=suffix, base_path=app.srcdir,
  File "/home/docs/checkouts/readthedocs.org/user_builds/toqito/envs/latest/lib/python3.11/site-packages/sphinx/ext/autosummary/generate.py", line 508, in generate_autosummary_docs
    name, obj, parent, modname = import_ivar_by_name(entry.name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/toqito/envs/latest/lib/python3.11/site-packages/sphinx/ext/autosummary/__init__.py", line 712, in import_ivar_by_name
    real_name, obj, parent, modname = import_by_name(name, prefixes)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/toqito/envs/latest/lib/python3.11/site-packages/sphinx/ext/autosummary/__init__.py", line 655, in import_by_name
    raise ImportExceptionGroup('no module named %s' % ' or '.join(tried), exceptions)
sphinx.ext.autosummary.ImportExceptionGroup: no module named toqito.channel_metrics

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/toqito/envs/latest/lib/python3.11/site-packages/sphinx/cmd/build.py", line 293, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/toqito/envs/latest/lib/python3.11/site-packages/sphinx/application.py", line 272, in __init__
    self._init_builder()
  File "/home/docs/checkouts/readthedocs.org/user_builds/toqito/envs/latest/lib/python3.11/site-packages/sphinx/application.py", line 343, in _init_builder
    self.events.emit('builder-inited')
  File "/home/docs/checkouts/readthedocs.org/user_builds/toqito/envs/latest/lib/python3.11/site-packages/sphinx/events.py", line 108, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function process_generate_options at 0x7f559ad2e840> for event 'builder-inited' threw an exception (exception: no module named toqito.channel_metrics)

Extension error (sphinx.ext.autosummary):
Handler <function process_generate_options at 0x7f559ad2e840> for event 'builder-inited' threw an exception (exception: no module named toqito.channel_metrics)
```

**Comment by vprusso** [comment]
Fixed the broken docs build (which was completely on me!) I added `sympy` as a dependency in the dev requirements, but it's needed for the docs as well. All fixed!

**Comment by vprusso** [comment]
Just fyi I did have to push something simple to the `requirements.txt` file in `docs/` to `master` so just fyi for updating your branches.

**Comment by purva-thakre** [comment]
Great! Thanks!

**Pull request merged**
