### PR TITLE
Adding matsumoto_fidelity feature

### PR DESCRIPTION
**Pull request by dfacoet**
## Description
This implements `matsumoto_fidelity` as described in #28, including documentation and tests.

The implementation is similar to that of `fidelity`, the main difference being that the direct calculation requires at least one of the density matrices to be invertible.
To work around this I adapted the QETLAB implementation: try to invert the matrix with largest determinant; if an error is raised, add a small number `eps` to it. Initially I tried to use machine epsilon, but it created stability problems with the square root. After some trial and error, I found `1e-8` to be a reasonable value (this is also what QETLAB uses).
This works because for singular matrices the limit of zero `eps` is the correct definition of the Matsumoto fidelity (eq. 1.6 in https://arxiv.org/abs/2006.06918). The QETLAB documentation states that the result is accurate to `1e-4`, which is consistent with what I see.

A possible improvement could be to check whether the matrices are singular (perhaps with `toqito.matrix_props.is_positive_definite`) and use the `cvxpy` solution if they are. This could be given as an option, to avoid introducing a `cvxpy` dependence.

Regarding the tests, I reproduced those of `fidelity`. One thing to note is that they are all for either equal states, or classical mixtures. In particular, `matsumoto_fidelity` and `fidelity` have the same behaviour for all the tests.

## Questions
-  [ ] Should we use `cvxpy` if both matrices are singular?
-  [x] Should we add more tests?

### CODE REVIEW

**Comment by vprusso** [comment]
Hi @dfacoet. Overall, looks pretty great!

A few comments: I also noticed that building the docs by navigating to the `toqito/docs` directory and running

```
make clean html
```

yields the following warning:

```
toqito.state_metrics.matsumoto_fidelity:58: WARNING: Explicit markup ends without a blank line; unexpected unindent.
```

W.r.t. your questions:

> Should we add more tests?

Looks like you achieved 100% coverage, which is great. More tests are always good, but at a minimum obtaining the 100% coverage is a great metric. It also looks like you have a pretty good set of tests, but if you notice any other edge cases, by all means, please do add them, but for now, it looks good. 

> Should we use `cvxpy` if both matrices are singular?

I could be missing something, but I would imagine so. Is there a reason why one would not want to do this?

**Comment by vprusso** [comment]
@dfacoet just following up to see where you are in the updates to this PR. I think it's 99% ready to go, but let me know if you have any questions of course as well. Cheers!

**Comment by dfacoet** [comment]
Hi @vprusso. Thank you for the review!

> yields the following warning:

This should be fixed by ae521707535e62a477a8a89ccbeaf0438ae26711.

> I could be missing something, but I would imagine so. Is there a reason why one would not want to do this

The way it is done at the moment (similar to QETLAB) is a bit blunt but reasonably accurate (~10^4) and avoids `cvxpy`, unless explicitly requested (if the input is a `cvxpy` variable).
I thought it could be desirable to know which method will be used, depending only on the input type, but I don't know if it is, which is why I asked.

A finer implementation could include an additional parameter such that if both determinants are smaller than the parameter, `cvxpy` is used. But I could be overthinking this for no good reason, and we can either leave it as it is, or use `cvxpy` whenever matrix inversion fails.

**Comment by vprusso** [comment]
Hi @dfacoet. Gotcha, those are all good points. I think for the sake of the task at hand though, I'd say this feature looks good to me. I'll go ahead and merge it in. Thanks again for your contribution!

**Pull request merged**
