### PR TITLE
Changes to workflow

### LINKED ISSUE #201: Label Workflows Properly
## Expected Behavior
All the jobs run by Github Actions are available in `.github/workflows/build-test-actions.yml`. They are labeled according to python versions. 

## Actual Behavior
It might be better to instead label the tests according to what is being tested:

- Run tests specific to Toqito (think of a better name)
- Codestyle: pylint, ~~pydocstyle, black, flake8~~ ruff (make both consistent with each other)
- Examples in docstrings (different issue for this: #289 )
- Build artifacts
- Code coverage
- Build documentation (figure out a workflow): Only need RTD Preview for a PR

The goal of this issue is to change how checks appear in a PR. Instead of what appears below, use labels in the above-itemized list. 
image

https://pre-commit.com/

Edit:~~ `pydocstyle` does not provide any info about the workflow passing.~~ Decided to remove `pydocstyle`.  
image

It might also be better if `pylint` orders all errors/warnings alphabetically.

### PR DESCRIPTION
**Pull request by purva-thakre**
## Description
Fixes #201 

## Todos
Notable points that this PR has either accomplished or will accomplish.
  -  [ ] TODO 1

## Questions
-  [ ] Question1

## Status
-  [x] Ready to go

### CODE REVIEW

**Comment by purva-thakre** [comment]
@vprusso I apologize in advance if you get inundated with a large number of notifications. I won't be able to locally test the changes in this PR!

**Comment by vprusso** [comment]
> @vprusso I apologize in advance if you get inundated with a large number of notifications. I won't be able to locally test the changes in this PR!

No worries. Charge ahead!

**Comment by purva-thakre** [comment]
@vprusso I am marking this ready for review. 

There were some additional things I was planning with this PR. But issues #342 and #341 show I will have to fix other problems first.

**Comment by purva-thakre** [comment]
Once this PR is approved, rebase before merging. 

Dependabot is now active. Quite a few changes will be made due to it.

**Review by vprusso — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
