### PR TITLE
[unitaryhack] Add `is_block_positive`.

### LINKED ISSUE #45: Feature: Is block-positive
Given an operator (matrix) determine if it is block-positive. 

The definition of block-positivity can be found in Section 2.2.5 in [arXiv:1207.1479](https://arxiv.org/abs/1207.1479).

Determining block-positivity is a very useful tool in the context of quantum state discrimination. Such an example application can be found in [arXiv:1408.6981](https://arxiv.org/abs/1408.6981). Roughly speaking, the utility is because the cone of block-positive operators constitutes the dual cone of separable operators--and hence determining block-positivity can be useful for proving separability results for certain quantum state discrimination schemes. 

An implementation of determining whether an operator is block-positive can be found in [QETLAB's `IsBlockPositive` function](http://www.qetlab.com/IsBlockPositive). This will be a useful reference implementation to test against. 

Will require feature that allows computing the S(k) norm

https://github.com/vprusso/toqito/issues/73

to be completed as a pre-requisite.

### PR DESCRIPTION
**Pull request by georgios-ts**
## Description
Closes #45

### CODE REVIEW

**Comment by georgios-ts** [comment]
On hold until #98 merges.

**Comment by vprusso** [comment]
Outstanding! This is great, @georgios-ts !

**Comment by nathanshammah** [comment]
Did you sign up on unitaryHACK? Cannot find you. Please sign up to be able to claim the bounties, https://unitaryhack.dev/signup/

**Comment by vprusso** [comment]
@georgios-ts did an outstanding job on this one. 

Also, for bookkeeping, @georgios-ts also closed https://github.com/vprusso/toqito/issues/76

**Comment by georgios-ts** [comment]
@nathanshammah Yeah, I've already signed up but I'll do it again if it's necessary!

**Pull request merged**
