### PR TITLE
Fix #478 : Rename shift and clock matrices to gen_pauli_x and gen_pauli_z

### LINKED ISSUE #478: Rename shift and clock matrices to gen_pauli_x and gen_pauli_z
The terminology for the "shift" and "clock" matrices is not necessarily well known in the quantum computing community, and in the context of quantum information, these matrices are more often referred to as the "generalized Pauli-X" and "generalized Pauli-Z" matrices. We should rename these.

We can still reference the matrices as is done in the functions, but we will want to explicitly point out that the generalized Pauli-X (shift) operator and generalized Pauli-Z (phase) operators are named as such.

### PR DESCRIPTION
**Pull request by MohitKambli**
## Description
As requested in #478, I have replaced all the variables/comments/function-names/file-names occurrences from shift to gen_pauli_x and clock to gen_pauli_z.
If at all there are any issues regarding these code changes, then do let me know.
Sincere apologies if I have missed any code to be changed or implemented a code incorrectly.
Kindly let me know if any changes are required.

## Todos
Notable points that this PR has either accomplished or will accomplish.
  -  [X] Name change of shift/clock to gen_pauli_x/gen_pauli_z.

## Questions
-  [ ] Question1

## Status
-  [ ] Ready to go

### CODE REVIEW

**Comment by purva-thakre** [comment]
@MohitKambli There are going to be some workflow failures based on the changes you introduced. Refer to the `Testing` and `code_style` sections in the docs. 

The `toqito/matrices` module has a folder labeled `tests` with unit tests for the functions in the module. 

You will also need to make changes to the examples in the respective function docstrings. 

https://toqito.readthedocs.io/en/latest/contributing.html#testing

**Comment by MohitKambli** [comment]
Hello @purva-thakre,
Hope you're doing well.
Sincere apologies for my mistakes.
I went through the `ruff ` and `pylint` documentation so that I can test my changes.
I figured out where I was going wrong and made changes accordingly.
Thank you for helping me out and letting me know about these code changes.
I have added a commit where I have made the potential changes.
Hope these changes help in resolving the issues I observed.
Sincere apologies if I messed up somewhere.

Thanks and Regards,
Mohit Kambli

**Comment by vprusso** [comment]
> @MohitKambli There are going to be some workflow failures based on the changes you introduced. Refer to the `Testing` and `code_style` sections in the docs. https://toqito.readthedocs.io/en/latest/contributing.html#testing
> 
> The `toqito/matrices` module has a folder labeled `tests` with unit tests for the functions in the module. These require changes as well.
> 
> Also make sure the functions you change are not used anywhere else: code of other functions or docstring examples of other functions. We have a workflow that checks for both.

Hi @MohitKambli. Looks good overall, but I believe you may need to address the comment here that @purva-thakre mentioned. Let us know if that doesn't make sense, and thanks again for your contribution! I think it's close!

**Comment by purva-thakre** [comment]
@vprusso I think this PR is good to go. The part with the `tests` folder won't apply here given the conversation in #485

**Comment by vprusso** [comment]
Awesome, also good on my end as well. Merge when ready, @MohitKambli (after you've addressed the docs issue as mentioned by @purva-thakre )

**Comment by MohitKambli** [comment]
Hello @vprusso and @purva-thakre,
Hope you're doing well.
As mentioned by @purva-thakre in the previous comment, I had made the code changes and executed the `ruff` and `pylint` commands for coding style and testing purposes respectively.
If there are any changes to make in the documentation or anywhere else, then do let me know.
I didn't quite get what needs to be done from my end.
Sincere apologies if I misunderstood anything or missed some part.

Thanks and Regards,
Mohit Kambli

**Comment by purva-thakre** [comment]
>If there are any changes to make in the documentation or anywhere else, then do let me know.

I think @vprusso's last comment is through his email. he might not have noticed that all workflow jobs pass. 

Thanks!

**Pull request merged**
