### PR TITLE
Pytest Warnings

### LINKED ISSUE #196: Warnings via pytest
## Expected Behavior

If `pytest` is used to run all the tests in `toqito/tests`, a bunch of warnings are raised. 

## Actual Behavior

```
=============================== warnings summary ===============================
../../../.cache/pypoetry/virtualenvs/toqito-QfgmswsN-py3.11/lib/python3.11/site-packages/coverage/pytracer.py:164
  /home/runner/.cache/pypoetry/virtualenvs/toqito-QfgmswsN-py3.11/lib/python3.11/site-packages/coverage/pytracer.py:164: DeprecationWarning: currentThread() is deprecated, use current_thread() instead
    self.thread = self.threading.currentThread()
../../../.cache/pypoetry/virtualenvs/toqito-QfgmswsN-py3.11/lib/python3.11/site-packages/pytest_cov/plugin.py:233
  /home/runner/.cache/pypoetry/virtualenvs/toqito-QfgmswsN-py3.11/lib/python3.11/site-packages/pytest_cov/plugin.py:233: PytestDeprecationWarning: The hookimpl CovPlugin.pytest_configure_node uses old-style configuration options (marks or attributes).
  Please use the pytest.hookimpl(optionalhook=True) decorator instead
   to configure the hooks.
   See https://docs.pytest.org/en/latest/deprecations.html#configuring-hook-specs-impls-using-markers
    def pytest_configure_node(self, node):
../../../.cache/pypoetry/virtualenvs/toqito-QfgmswsN-py3.11/lib/python3.11/site-packages/pytest_cov/plugin.py:242
  /home/runner/.cache/pypoetry/virtualenvs/toqito-QfgmswsN-py3.11/lib/python3.11/site-packages/pytest_cov/plugin.py:242: PytestDeprecationWarning: The hookimpl CovPlugin.pytest_testnodedown uses old-style configuration options (marks or attributes).
  Please use the pytest.hookimpl(optionalhook=True) decorator instead
   to configure the hooks.
   See https://docs.pytest.org/en/latest/deprecations.html#configuring-hook-specs-impls-using-markers
    def pytest_testnodedown(self, node, error):
../../../.cache/pypoetry/virtualenvs/toqito-QfgmswsN-py3.11/lib/python3.11/site-packages/cvxpy/reductions/solvers/conic_solvers/sdpa_conif.py:136
  /home/runner/.cache/pypoetry/virtualenvs/toqito-QfgmswsN-py3.11/lib/python3.11/site-packages/cvxpy/reductions/solvers/conic_solvers/sdpa_conif.py:136: DeprecationWarning: invalid escape sequence '\i'
    """
../../../.cache/pypoetry/virtualenvs/toqito-QfgmswsN-py3.11/lib/python3.11/site-packages/cvxpy/reductions/cone2cone/soc2psd.py:49
  /home/runner/.cache/pypoetry/virtualenvs/toqito-QfgmswsN-py3.11/lib/python3.11/site-packages/cvxpy/reductions/cone2cone/soc2psd.py:49: DeprecationWarning: invalid escape sequence '\l'
    """
tests/test_channel_metrics/test_completely_bounded_trace_norm.py: 4 warnings
tests/test_helper/test_npa_constraints.py: 2 warnings
tests/test_matrices/test_gell_mann.py: 1 warning
tests/test_matrices/test_gen_gell_mann.py: 1 warning
tests/test_matrix_props/test_is_block_positive.py: 2 warnings
tests/test_nonlocal_games/test_extended_nonlocal_game.py: 6 warnings
tests/test_nonlocal_games/test_nonlocal_game.py: 7 warnings
tests/test_state_opt/test_ppt_distinguishability.py: 1 warning
tests/test_state_opt/test_symmetric_extension_hierarchy.py: 3 warnings
tests/test_state_props/test_has_symmetric_extension.py: 1 warning
  /home/runner/.cache/pypoetry/virtualenvs/toqito-QfgmswsN-py3.11/lib/python3.11/site-packages/scipy/sparse/_sputils.py:44: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
  See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
    upcast = np.find_common_type(args, [])
tests/test_channel_metrics/test_fidelity_of_separability.py: 2 warnings
tests/test_matrix_props/test_is_block_positive.py: 2 warnings
tests/test_perms/test_symmetric_projection.py: 8 warnings
tests/test_state_metrics/test_fidelity_of_separability.py: 1 warning
tests/test_state_opt/test_symmetric_extension_hierarchy.py: 2 warnings
tests/test_state_props/test_has_symmetric_extension.py: 1 warning
tests/test_states/test_breuer.py: 1 warning
  /home/runner/work/toqito/toqito/toqito/perms/symmetric_projection.py:90: DeprecationWarning: `np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`
    p_fac = np.math.factorial(p_val)
tests/test_matrix_ops/test_vectors_to_gram_matrix.py::test_vectors_to_gram_matrix
tests/test_matrix_ops/test_vectors_to_gram_matrix.py::test_vectors_to_gram_matrix
tests/test_matrix_ops/test_vectors_to_gram_matrix.py::test_vectors_to_gram_matrix
tests/test_matrix_ops/test_vectors_to_gram_matrix.py::test_vectors_to_gram_matrix
tests/test_matrix_ops/test_vectors_to_gram_matrix.py::test_vectors_to_gram_matrix
tests/test_matrix_ops/test_vectors_to_gram_matrix.py::test_vectors_to_gram_matrix
tests/test_matrix_ops/test_vectors_to_gram_matrix.py::test_vectors_to_gram_matrix
tests/test_matrix_ops/test_vectors_to_gram_matrix.py::test_vectors_to_gram_matrix
tests/test_matrix_ops/test_vectors_to_gram_matrix.py::test_vectors_to_gram_matrix
  /home/runner/work/toqito/toqito/toqito/matrix_ops/vectors_to_gram_matrix.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
    gram[i, j] = vectors[i].conj().T @ vectors[j].reshape(-1, 1)
tests/test_matrix_props/test_is_block_positive.py::test_swap_operator_is_block_positive[4]
tests/test_matrix_props/test_is_block_positive.py::test_is_block_positive
tests/test_state_props/test_has_symmetric_extension.py::test_has_symmetric_extension_level_2_entangled_false_ppt
  /home/runner/.cache/pypoetry/virtualenvs/toqito-QfgmswsN-py3.11/lib/python3.11/site-packages/cvxpy/problems/problem.py:164: UserWarning: Constraint #2 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
    warnings.warn(f"Constraint #{i} contains too many subexpressions. "
tests/test_matrix_props/test_is_block_positive.py::test_choi_is_block_positive
tests/test_matrix_props/test_is_block_positive.py::test_is_block_positive
tests/test_state_props/test_has_symmetric_extension.py::test_has_symmetric_extension_level_2_entangled_false_ppt
  /home/runner/.cache/pypoetry/virtualenvs/toqito-QfgmswsN-py3.11/lib/python3.11/site-packages/cvxpy/problems/problem.py:164: UserWarning: Constraint #4 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
    warnings.warn(f"Constraint #{i} contains too many subexpressions. "
tests/test_matrix_props/test_is_block_positive.py::test_is_block_positive
tests/test_state_props/test_has_symmetric_extension.py::test_has_symmetric_extension_level_2_entangled_false_ppt
  /home/runner/.cache/pypoetry/virtualenvs/toqito-QfgmswsN-py3.11/lib/python3.11/site-packages/cvxpy/problems/problem.py:164: UserWarning: Constraint #3 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
    warnings.warn(f"Constraint #{i} contains too many subexpressions. "
tests/test_state_props/test_has_symmetric_extension.py::test_has_symmetric_extension_level_2_entangled_false_ppt
  /home/runner/.cache/pypoetry/virtualenvs/toqito-QfgmswsN-py3.11/lib/python3.11/site-packages/cvxpy/problems/problem.py:164: UserWarning: Constraint #5 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
    warnings.warn(f"Constraint #{i} contains too many subexpressions. "
tests/test_state_props/test_log_negativity.py::test_log_negativity_rho
tests/test_state_props/test_log_negativity.py::test_log_negativity_rho
  /home/runner/work/toqito/toqito/toqito/state_props/log_negativity.py:77: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
    dim = [int(x) for x in dim]
tests/test_state_props/test_negativity.py::test_negativity_rho
tests/test_state_props/test_negativity.py::test_negativity_rho
  /home/runner/work/toqito/toqito/toqito/state_props/negativity.py:78: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
    dim = [int(x) for x in dim]
```

## Steps to Reproduce the Problem

```
pyenv activate venv_for_toqito
cd toqito/tests
pytest
```

## Specifications

pytest 7.3.1, Python 3.9.16, toqito 1.0.5

### PR DESCRIPTION
**Pull request by purva-thakre**
## Description
Fixes #196 

## Todos
Notable points that this PR has either accomplished or will accomplish.
  -  [ ] TODO 1

## Questions
-  [ ] Question1

## Status
-  [ ] Ready to go

### CODE REVIEW

**Comment by purva-thakre** [comment]
@vprusso Am I right to assume this warning is due to some unresolved deprecation warning in `scipy` and unrelated to `toqito`? 

```
tests/test_channel_metrics/test_completely_bounded_trace_norm.py::test_cb_trace_norm_unitaries_channel
tests/test_channel_metrics/test_completely_bounded_trace_norm.py::test_cb_trace_norm_unitaries_channel
tests/test_channel_metrics/test_completely_bounded_trace_norm.py::test_cb_trace_norm_unitaries_channel
tests/test_channel_metrics/test_completely_bounded_trace_norm.py::test_cb_trace_norm_unitaries_channel
  /root_path/.pyenv/versions/3.11.5/envs/venv_poetry/lib/python3.11/site-packages/scipy/sparse/_sputils.py:44: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
  See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
    upcast = np.find_common_type(args, [])

```

**Comment by vprusso** [comment]
> @vprusso Am I right to assume this warning is due to some unresolved deprecation warning in `scipy` and unrelated to `toqito`?
> 
> ```
> tests/test_channel_metrics/test_completely_bounded_trace_norm.py::test_cb_trace_norm_unitaries_channel
> tests/test_channel_metrics/test_completely_bounded_trace_norm.py::test_cb_trace_norm_unitaries_channel
> tests/test_channel_metrics/test_completely_bounded_trace_norm.py::test_cb_trace_norm_unitaries_channel
> tests/test_channel_metrics/test_completely_bounded_trace_norm.py::test_cb_trace_norm_unitaries_channel
>   /root_path/.pyenv/versions/3.11.5/envs/venv_poetry/lib/python3.11/site-packages/scipy/sparse/_sputils.py:44: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
>   See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
>     upcast = np.find_common_type(args, [])
> ```
> 
> Edit: Similar issues for `cvxpy` and `pytest`. I think these warnings won't be fixed in this repo. https://github.com/vprusso/toqito/actions/runs/6686601698/job/18166160699?pr=210#step:5:718 https://github.com/vprusso/toqito/actions/runs/6686601698/job/18166160699?pr=210#step:5:668

Yes, that seems to be correct. As it appears to be complaining about `np.find_common_type` (which we don't use).

However, when attempting to run the tests for this module I don't appear to be obtaining the same warning. 

Indeed, when running it, I do obtain `scipy` warnings, but they are different:

```
% pytest tests/test_channel_metrics/test_completely_bounded_trace_norm.py 
==================================================================== test session starts =====================================================================
platform darwin -- Python 3.10.11, pytest-7.3.1, pluggy-1.0.0
rootdir: /Users/vrusso/Projects/research/toqito
collected 3 items                                                                                                                                            

tests/test_channel_metrics/test_completely_bounded_trace_norm.py ...                                                                                   [100%]

====================================================================== warnings summary ======================================================================
toqito/matrices/gell_mann.py:8
  /Users/vrusso/Projects/research/toqito/toqito/matrices/gell_mann.py:8: DeprecationWarning: Please use `csr_matrix` from the `scipy.sparse` namespace, the `scipy.sparse.csr` namespace is deprecated.
    def gell_mann(ind: int, is_sparse: bool = False) -> np.ndarray | scipy.sparse.csr.csr_matrix:

toqito/matrices/pauli.py:13
  /Users/vrusso/Projects/research/toqito/toqito/matrices/pauli.py:13: DeprecationWarning: Please use `csr_matrix` from the `scipy.sparse` namespace, the `scipy.sparse.csr` namespace is deprecated.
    ) -> np.ndarray | sparse.csr.csr_matrix:

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=============================================================== 3 passed, 2 warnings in 2.47s ================================================================
```

For reference, I tried the above with `scipy==1.10.1` and `numpy==1.26.1`. I also noticed that when attempting to upgrade `scipy` to the latest version it appears to throw some errors (which might be due to some updates that `cvx` needs to make on their end from what I can tell).

**Comment by purva-thakre** [comment]
@vprusso The errors you get with `scipy` should be fixed with the latest commit in this branch. 

Yes, I think `cvx` warnings and 1 `pytest` warning could be ignored for now. 

Interesting that you don't get the same errors as me. This time, I did use `poetry` for a brand new virtual environment. 

However, I just figured out this environment has the same import issue that should have been fixed in #206. All tests pass in `toqito/tests` but if I go inside some `toqito/tests/test_something` and then run pytest, some tests due to `Module not found`.

**Comment by purva-thakre** [comment]
Closing this PR because I messed up my git rebase.

**Pull request closed without merging**
