### PR TITLE
Format with black (#180)

### PR DESCRIPTION
**Pull request by FrankXenarthra**
## Description
Automatic changes done via black linting tool on the python files

## Todos
Notable points that this PR has either accomplished or will accomplish.
  -  [ ] Review to check if all suggestions should be implemented

## Questions
-  [ ] None

## Status
-  [ ] Ready to go

### CODE REVIEW

**Comment by vprusso** [comment]
Hi @FrankXenarthra . Thanks for opening this PR! Just wanted to confirm that the status of this PR is still not "ready to go" as indicated by the checkbox. If that's the case, no worries, don't mean to rush or pester, just wanted to make sure I'm not leaving you hanging :) 

Let me know if there's anything I can help out on, and thanks again for your contribution!

**Comment by vprusso** [comment]
Excellent. Thank you again for your great contribution, @FrankXenarthra !

Merging away. Thank you again for your interest and contribution to the toqito project. I hope to see you around again!

**Comment by FrankXenarthra** [comment]
@vprusso I'm very happy that I could be part of this project now. The merged PR was still the old one without the flake8 configuration file to ensure the Black compatibility. I created a new PR for this: https://github.com/vprusso/toqito/pull/189 I
If you think these two should be in one commit and the merged PR commit and its additional merge commit should be reverted, let me know please. Then I will create a combined commit.

If still interested I would also proceed to implement the checks via Github Actions.

**Comment by vprusso** [comment]
That's great, I would love more input on the GitHub Actions content specifically. Automating these types of things has been something on my list for quite a while, so if you have some expertise and approach for putting the pieces together, the project would greatly benefit from that and I would be much obliged. Thank you again for your help and contribution!

**Pull request merged**
