### PR TITLE
AutoAPI + RTD theme: members ordering

### LINKED ISSUE #446: AutoAPI does not organize modules properly
Tried `groupwise` and `alphabetical` ordering to change the member ordering in `API reference`. 

image

`make clean html` worked locally where the member did change. 

But for some reason, both fail to work for the RTD build in docs.

https://toqito.readthedocs.io/en/latest/autoapi/index.html 

https://sphinx-autoapi.readthedocs.io/en/latest/reference/config.html#confval-autoapi_member_order

image

### PR DESCRIPTION
**Pull request by purva-thakre**
## Description
Fixes #446 

1. https://stackoverflow.com/questions/5599254/how-to-use-sphinxs-autodoc-to-document-a-classs-init-self-method
2. https://github.com/readthedocs/sphinx-autoapi/blob/main/docs/reference/templates.rst
3. https://sphinx-autoapi.readthedocs.io/en/latest/reference/directives.html
4. https://sphinx-rtd-trial.readthedocs.io/en/1.0.8/config.html
5. https://docs.readthedocs.io/en/stable/config-file/v2.html#build

## Todos
Notable points that this PR has either accomplished or will accomplish.
  -  [ ] TODO 1

## Questions
-  [ ] Question1

## Status
-  [ ] Ready to go

### CODE REVIEW

**Comment by purva-thakre** [comment]
It might be better to go through the output of the raw RTD build to understand why the changes I see locally don't appear in the RTD build. 

https://readthedocs.org/projects/toqito/builds/23296721/
https://readthedocs.org/api/v2/build/23296721.txt

When I use `autoapi_member_order = 'alphabetical'`, local build is completely different from the RTD build for this PR. The local build is still not perfect but it does change the ordering compared to the RTD build. 

I use `make clean html` locally whereas RTD uses `conf.py` somehow without the `clean` option. See the first RTD build link in this comment. 

```
python -m sphinx -T -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html
```
Options for sphix-build: https://www.sphinx-doc.org/en/master/man/sphinx-build.html#sphinx-build

Locally built API reference             |  RTD built API reference
:-------------------------:|:-------------------------:
image  | image

**Comment by purva-thakre** [comment]
Seems like manually listing the modules alphabetically does work. Don't need to slog through the raw output of the RTD build. 

image

Not exactly perfect as the goal of switching to `AutoAPI` was to get rid of the overhead of maintaining `.rst` files. In this case, there's only 1 file though. 

image

All that's left to do is to customize the `API Reference` layout. We want to get rid of the `Submodules, Module Contents and Functions` links. 

image

A really nice tutorial for how to customize this layout is available: https://bylr.info/articles/2022/05/10/api-doc-with-sphinx-autoapi/#autoapi-objects

AutoAPI docs for templates: https://sphinx-autoapi.readthedocs.io/en/latest/reference/templates.html#templates

**Comment by purva-thakre** [comment]
Before marking this PR ready for review, update the instructions related to `autosummary` in docs. 

It might also be better to change the order of main items in the sidebar. New order could be:

1. Getting Started
2. Introductory Tutorial
3. Additional Tutorials
4. Contributing Guide
5. Code of Conduct
6. API Reference
7. References

**Comment by purva-thakre** [comment]
@vprusso I have managed to get the `API Reference` page to appear how I wanted it to be. 

Do you want to further customize the page's appearance in some way? 

https://toqito--448.org.readthedocs.build/en/448/autoapi_members.html

**Comment by vprusso** [comment]
> @vprusso I have managed to get the `API Reference` page to appear how I wanted it to be.
> 
> Do you want to further customize the page's appearance in some way?
> 
> https://toqito--448.org.readthedocs.build/en/448/autoapi_members.html
> 
> Feel free to review this PR as well.

That looks great! Nice work, @purva-thakre !

**Pull request merged**
