### PR TITLE
Inner outer products

### PR DESCRIPTION
**Pull request by juliusw352**
## Description
Added inner_product and outer_product, as requested in issue #105.
I have been unable to run pytest, as it returns errors that I don't quite understand related to unvec.py, a file that I have not edited.

I've never contributed to an open source project before, so I tried to stick quite closely to the format of the other features in the matrix_ops category. As such, any feedback is much appreciated.

## Todos
  -  [x] Create inner_product and outer_product
  -  [x] Create documentation for the above
  -  [x] Create test cases
  -  [x] Run test cases

## Status
-  [x] Tests still need to be run, but other than that it seems fairly ready. 

## Questions
 - I'm currently working on the final project for my Bachelor's degree, which is related to nonlocal games. I'd love to contribute further to toqito – are there any particular features related to nonlocal games (beyond what is already listed in the issues tab) that I might be able to help out with?

### CODE REVIEW

**Comment by vprusso** [comment]
Hi Julius,

First of all, thank you for taking the time to contribute to the `toqito` project! It's wonderful to have new contributors!

Regarding this PR, for some reason, I'm not able to see your branch after running a `git fetch`. Typically, running this command should populate the branch listing with any of the PRs but for some reason, I'm not seeing your branch on my end.

Also, could you tell me what the issue is with `unvec`? I'll see if I can replicate that issue here on my end as well. 

Thanks again, and let me know if I can lend a hand in getting this over the fence!

**Comment by juliusw352** [comment]
Hi,

I am unsure on how to resolve the `git fetch` issue. Could it be that some upstream setting on my branch is incorrect?

On the testing errors: executing `pytest` in the `test_matrix_ops` directory, I get the same error for all five files:

```
_________________ ERROR collecting tests/test_matrix_ops/test_inner_product.py _________________
test_inner_product.py:4: in <module>
    from toqito.matrix_ops import inner_product
../../toqito/matrix_ops/__init__.py:4: in <module>
    from toqito.matrix_ops.unvec import unvec
../../toqito/matrix_ops/unvec.py:5: in <module>
    def unvec(vector: np.ndarray, shape: list[int] = None) -> np.ndarray:
E   TypeError: 'type' object is not subscriptable
```

with all of them pointing to `unvec.py`.

**Comment by vprusso** [comment]
> I am unsure on how to resolve the git fetch issue. Could it be that some upstream setting on my branch is incorrect?

It's possible. Perhaps you could tell me the workflow you have when you created the branch. I unfortunately am not able to see anything on my end regarding the branch which is strange, because you clearly have created a PR which (I would imagine) would be accessible on my end. 

If our analysis does not yield any resolution, once the tests are fixed, we can merge and I fix after the fact as a last ditch effort, but I am a bit curious as to what might be going on there :)

> On the testing errors: executing pytest in the test_matrix_ops directory, I get the same error for all five files:
Ah, so this looks like you might be using an older version of Python when running the tests. Python 3.7 supports type hints that look like:

```python
def f(x: list[int]):
    ...
```

whereas, in earlier versions of Python, one had to do:

```python
from typing import List

def f(x: List[int]):
    ...
```

Are you using `poetry` to invoke and run the environment by chance?

**Comment by juliusw352** [comment]
I tried to clone the `vprusso/toqito` repository and managed to `fetch` my branch with the help of [this Stackoverflow post](https://stackoverflow.com/questions/27567846/how-can-i-check-out-a-github-pull-request-with-git), running `git fetch origin pull/136/head:innerOuterProducts`.

Concerning the testing, I've been trying to run the tests with `python3 -m pytest`, with pytest 7.2.0 and Python 3.8.10, and have found myself getting the same errors.

**Comment by vprusso** [comment]
Hi @juliusw352 ,

Thanks for providing that extra context! The PR looks good. I think the only thing to mention is that one of the outer product tests is checking for the incorrect expected result. Namely:

```python
def test_outer_product_negative():
    """Test with two vectors, with negative input/output values."""

    v1, v2 = np.array([-1,2,3]), np.array([4,5,6])
    expected_res = np.array([[-4,5,6],[-8,10,12],[-12,15,18]])
    np.testing.assert_equal(outer_product(v1, v2), expected_res)
```

should be:

```python
def test_outer_product_negative():
    """Test with two vectors, with negative input/output values."""

    v1, v2 = np.array([-1,2,3]), np.array([4,5,6])
    expected_res = np.array([[-4,-5,-6],[8,10,12],[12,15,18]])
    np.testing.assert_equal(outer_product(v1, v2), expected_res)
```

Aside from that though, I did not encounter any issues with the `unvec` function (Again, I think that might be due to the fact that you are running Python 3.8 which does *not* have support for native type-hints). Consult this SO post for more info on that:
https://stackoverflow.com/questions/39458193/using-list-tuple-etc-from-typing-vs-directly-referring-type-as-list-tuple-etc

The long and short of it is that Python 3.9+ supports things like:

```python
def f(x: list[str]):
    ...
```

where < Python 3.9 requires:

```python
from typing import List

def f(x: List[str]):
    ...
```

In any case, if you are able to fix that one breaking test, the PR looks good! Thank you again for your contribution, and if you are generally interested in the nonlocal game side of things would be happy to chat about some features on that fron that might be of interest to you!

**Comment by vprusso** [comment]
Hi @juliusw352 

> I have fixed the test case, thanks for pointing it out.
> I have also finally managed to install Python 3.9, and you are right - the tests work perfectly fine now.

Awesome! That's great to hear :) Happy to know that you're also seeing the tests behave properly on your end--that's excellent.

> In terms of working on the nonlocal games side of things, I am currently trying to implement parallel repetition in the classical case for XOR games, so I have my hands full for the moment, but I would love to have a conversation once that is done!

Very cool! Definitely happy to be kept in the loop on that one--especially if I can lend a hand in helping out. 

On another note, the UnitaryFund will be putting on UnitaryHack in the early spring of this year. If you're not familiar, this is a yearly hackathon that focuses on adding new features and fixing bugs for open-source quantum-themed software projects. For the past two years, the `toqito` project has been a participating project, and I hope to include it this year as well. 

As is usual with these types of hackathons, certain projects offer cash bounties for their completion. I've had a great time participating in these events as a maintainer, and I hope you consider participating and contributing to `toqito` when the hackathon occurs!

For context, I'll put the link to last year's UnitaryHack here:
https://unitaryhack.dev/ 

In the meantime, happy to chat with you about nonlocal games and interesting problems that might lend themselves nicely to `toqito` :)

**Comment by vprusso** [comment]
Great! I'll go ahead and merge this PR. 

Thank you again for your contribution to `toqito`, @juliusw352 !

**Pull request merged**
